### ISSUE TITLE
make individual thematic search result types 'optional'

### ISSUE THREAD

**Issue by jgravois** [CodeForAsheville/simplicity-esri#1]
based on what we talked about at #cfasummit, should we pick a single thematic topic (ie: crime or something else) to start with for the rewrite?

**Comment by jgravois** [comment]
also, should we continue to point at your AWS instance for now?  i'd also be happy to set up some free esri hosted services with a couple of your shapefiles if you want to test something independent.

**Comment by carlyleec** [comment]
I think just picking one topic, like crime, is good way to move forward. Lets get that working, and then start to figure out ways to more easily scale out to more topics. Lets continue to use the City of Asheville's AWS instance for now to get all the functionality down, and we can try to see how it'll work with other datasets. If we design it right it should just work.
